define('mods/tpl/blogInflance', function(require, exports, module){
	module.exports = [
    '<#et tpl data>',
    	'<ul>',
     	'<#list data as list>',
				'<li>',
					'<#if (data.firstDate)>',
						'<#if (list_index == 0)>',
							'<div class="li li1 iconcolor_1"><span class="icon_list icon_1"></span>1</div>',
						'<#elseif (list_index == 1)>',
							'<div class="li li1 iconcolor_2"><span class="icon_list icon_2"></span>2</div>',
						'<#elseif (list_index == 2)>',
							'<div class="li li1 iconcolor_3"><span class="icon_list icon_3"></span>3</div>',
						'<#else>',
							'<div class="li li1">${list.indexNum}</div>',
						'</#if>',
					'<#else>',
						'<div class="li li1">${list.indexNum}</div>',
					'</#if>',
				        '<div class="li li2">${list.meidanewname}</div>',
				        '<div class="li li3">',
				        	/*
				        	'<#if (list.influenceChange < 0)>',
								'<span class="icon_4"></span>',
								'${list.changeNumber}',
							'<#elseif (list.influenceChange > 0)>',
								'<span class="icon_5"></span>',
								'${list.changeNumber}',
							'<#else>',*/
								'<span class="greybar"></span>',
							//'</#if>',
						'</div>',
				        '<div class="li li4">${list.influence}</div>',
				        '<div class="li li5">',
				        	'<#if (list.weibopower > 0)>',
				        	'<a class="color_${list.weibopower}" target="_blank" href="http://weibo.com/u/${list.weibouid}">',
				        	          '<div class="bar">',
				        	            '<div class="barin"></div>',
				        	            '<div class="size">${list.weiboinfluence}</div>',
				        	          '</div>',
				        	          '<div class="txt">微博主页</div>',
				        	 '</a>',
				        	 '<#else>',
				        	 '<span class="greybar_1"></span>',
				        	 '</#if>',
				          '</div>',
				        '<div class="li li5">',
				        	'<#if (list.weixinpower > 0)>',
				       		'<a class="color_${list.weixinpower}" href="#">',
				       		          '<div class="bar">',
				       		            '<div class="barin"></div>',
				       		            '<div class="size">${list.weixininfluence}</div>',
				       		          '</div>',
				       		'</a>',
				       		'<div class="txt_1">ID：${list.meidanewid}</div>',
				       		 '<#else>',
				        	 '<span class="greybar_1"></span>',
				        	 '</#if>',
				          
				        '</div>',
				        '<div class="li li5">',
				        	'<#if (list.blogpower > 0)>',
				        	'<a class="color_${list.blogpower}" target="_blank" href="http://blog.sina.com.cn/u/${list.bloguid}">',
				        	          '<div class="bar">',
				        	            '<div class="barin"></div>',
				        	            '<div class="size">${list.bloginfluence}</div>',
				        	          '</div>',
				        	          '<div class="txt">博客主页</div>',
				        	 '</a>',
				        	 '<#else>',
				        	 '<span class="greybar_1"></span>',
				        	 '</#if>',
				        
				          '</div>',
				     '</li>',
		'</#list>',
		'</ul>', 
		'<#if (data.more)>',
		'<div class="pages"><a class="page disable" node="prev" href="#">上一页</a>',
		  '<a class="cur" node="page_one" href="#">1</a>',
		  '<a href="#" node="page_two">2</a>',
		  '<a class="page" node="next" href="#">下一页</a></div>',
		  
		'</div>',  
		'<#else>',
		'</#if>',
    '</#et>'
  ].join('');


});