
/**
 * @fileoverview 昵称活动页浮层面板展示所有模版
 * @author Liu Xiaoyue | xiaoyue3@staff
 * @created 2013-08-20
 */
var layerTplNick = ['<div class="emPop" id="#{layerWrap}">',
                        '<div class="bd">',
                            '<a href="javascript:;" class="close" title="关闭" id="#{closeLayer}"></a>',
                            '<div class="txtbd txtbd_h" style="display:none;" showLayer = "success_0">',
                                '<div class="ico"><img width="96" height="95" src="http://simg.sinajs.cn/blog7style/images/activity/unique/icon_xr.png" alt="新锐博主"></div>',
                                '<div class="txt">',
                                    '<p>恭喜你,<span>已抢占成功！</span><br></p>',
                                    '<p class="f12">目前已拥有全新浪唯一的昵称 不信你就搜索试试</p>',
                                    '<a href="javascript:;" class="btn" title="立即抽奖" id="getPrize" onclick="return false;">立即抽奖</a>',
                                '</div>',
                            '</div>',
                            '<div class="txtbd prompt_m" style="display:none;" showLayer = "prize_0">',
                                '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_cry.png" alt="" /></div>',
                                '<div class="txt02">',
                                '<p>恭喜您:抽中<span>"微博会员模板体验卡"</span></p>',
                                '<p>请在一个月内去微博激活</p>',
                                '</div>',
                            '</div>',
                            '<div class="txtbd prompt_m" style="display:none;" showLayer = "prize_1">',
                                '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_cry.png" alt="" /></div>',
                                '<div class="txt02">',
                                '<p>恭喜您:抽中<span>"微博会员自定义头图体验卡"</span></p>',
                                '<p>请在一个月内去微博激活</p>',
                                '</div>',
                            '</div>',
                            '<div class="txtbd prompt_m" style="display:none;" showLayer = "prize_2">',
                                '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_cry.png" alt="" /></div>',
                                '<div class="txt02">',
                                '<p>恭喜您:抽中<span>"微博会员7天综合体验卡"</span></p>',
                                '<p>请在一个月内去微博激活</p>',
                                '</div>',
                            '</div>',
                            '<div class="txtbd prompt_m" style="display:none;" showLayer = "prize_3">',
                                '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_cry.png" alt="" /></div>',
                                '<div class="txt02">',
                                '<p>恭喜您:抽中<span>"微博会员15天综合体验卡"</span></p>',
                                '<p>请在一个月内去微博激活</p>',
                                '</div>',
                            '</div>',
                            '<div class="txtbd prompt_m" style="display:none;" showLayer = "prize_4">',
                                '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_cry.png" alt="" /></div>',
                                '<div class="txt02">',
                                '<p>恭喜您:抽中<span>"专享微盘100G空间"</span></p>',
                                '<p>激活码已发到博客系统消息中，请您注意查收</p>',
                                '</div>',
                            '</div>',
                            '<div class="share" style="display:none;" showLayer="b_success_0"><div class="choice" id="shareNA_weibo" type="1"></div><span>分享到微博</span><div class="choice" id="shareNA_blog" type="1"></div><span>分享到博客</span></div>',
                            '<div class="txtbd" showLayer="blank_0">',
                                '<div class="txt tit" style="display:none;" showLayer = "1_0">',
                                    '<div>',
                                        '<p style="display:none;" showLayer = "1_0_1">您还没有<a href="#">开通博客</a>，开通后即可抢占</p>',
                                        '<p style="display:none;" showLayer = "1_0_5">网络繁忙，请稍后再试</p>',
                                        '<p style="display:none;" showLayer = "1_0_2">您的荣誉徽章已经点亮 </p>',
                                        '<p style="display:none;" showLayer = "1_0_3">您还没有<a href="#">开通微博</a>，开通后立即抢占</p>',
                                        '<p style="display:none;" showLayer = "1_0_4">您还不是新浪用户请先<a href="http://login.sina.com.cn/signup/signin.php" target="_blank">登录</a><a href="https://login.sina.com.cn/signup/signup?entry=blog" target="_blank">注册</a></p>',
                                    '</div>',
                                    '<div style="display:none;" showLayer = "1_1_0">',
                                        '<p>您的昵称已经唯一，不需要重复抢占</p>',
                                        // '<p class="f12 txt03">还可以通过搜索功能：<a href="#textfield" class="underline" id="tryNickTpl2">换个昵称试试</a></p>',
                                    '</div>',
                                '</div>',
                                '<div class="txt txt_h" style="display:none;" showLayer = "2_0">',
                                    '<p>您的博客昵称已被占用</p>',
                                    '<p class="f12" style="display:none;" showLayer = "2_0_1">直接用微博昵称<a href="javascript:;" id="tjWnick"></a>抢占</p>',
                                    '<p class="f12" style="display:none;" showLayer = "2_0_2">可以使用推荐的昵称：<span id="tjNick"></span></p>',
                                    '<p class="f12" showLayer = "2_3">还可以通过搜索功能：<a href="#search" class="underline" id="tryNickTpl">换个昵称试试</a></p>',
                                '</div>',
                                '<div class="txt txt_h" style="display:none;" showLayer = "5_0">',
                                    '<p>蓝v身份用户修改昵称需要重新审核，有掉v风险</p>',
                                    '<p class="f12" style="display:none;" showLayer = "5_0_1">建议您用微博昵称<a href="javascript:;" id="tjWnick1"></a>抢占</p>',
                                '</div>',
                                '<div style="display:none;" showLayer = "3_0">',
                                    '<div class="prompt"><img width="55" height="54" src="http://simg.sinajs.cn/blog7style/images/activity/unique/ico_happy.png" alt="" /></div>',
                                    '<div class="txt02">',
                                        '<p>很遗憾，神马都木有抽中</p>',
                                        '<p>感谢您的参与</p>',
                                    '</div>',
                                '</div>',
                                '<div class="txt txt_h" style="display:none;" showLayer = "4_0">',
                                    '<p>您的博客与微博昵称不一致</p>',
                                    '<p class="f12" style="display:none;" showLayer = "4_0_1">直接用博客昵称<a href="javascript:;" id="tjBlogNick"></a>抢占</p>',
                                    '<p class="f12" style="display:none;" showLayer = "4_0_2">可以使用推荐的昵称：<span id="tjBlogNick"></span></p>',
                                    '<p class="f12" showLayer = "4_3">还可以通过搜索功能：<a href="#search" class="underline" id="searchBlogNick">换个昵称试试</a></p>',
                                '</div>',
                            '</div>',
                            '<div class="btn_c">',
                                '<div style="display:none;" showLayer = "b_7"><a href="#search" class="btn" title="搜一搜" id="ssBtn">搜一搜</a></div>',
                                '<div style="display:none;" showLayer = "b_0">使用推荐昵称 <a href="javascript:;" class="btn" title="立即点亮" id="qiangzhan1">立即抢占</a></div>',
                                '<div style="display:none;" showLayer = "b_1"><a href="javascript:;" class="btn" title="知道了" id="knowBtn">知道了</a></div>',
                                '<div style="display:none;" showLayer = "b_2"><a href="javascript:;" class="btn" title="一键开通" id="openBlogBtn">一键开通</a></div>',
                                '<div style="display:none;" showLayer = "b_6"><a href="javascript:;" class="btn" title="一键开通" id="openweiboBtn">一键开通</a></div>',
                                '<div style="display:none;" showLayer = "b_5">直接用微博昵称 <a href="javascript:;" class="btn" title="立即点亮" id="qiangzhan">立即抢占</a></div>',
                                '<div style="display:none;" showLayer = "b_8">直接用博客昵称 <a href="javascript:;" class="btn" title="立即点亮" id="qiangzhanBlogNick">立即抢占</a></div>',
                            '</div>',
                        '</div>',
                    '</div>'
    ];
scope.nickActivityLayerTpl = layerTplNick.join("");  