/**
 * @fileoverview 表情的模板(带小表情)
 * @author Random | YangHao@staff.sina.com.cn
 * @created 2009-08-31
 */

scope.faceDialogTemplate=[
	'<table id="#{entity}" class="CP_w">',
		'<thead id="#{titleBar}">',
			'<tr>',
				'<th class="tLeft"><span></span></th>',
				'<th class="tMid">',
					'<div class="bLyTop">',
						'<strong id="#{titleName}">插入表情</strong>',
						'<cite><a id="#{btnClose}" href="javascript:;" class="CP_w_shut" title="关闭">关闭</a></cite>',
					'</div>',
				'</th>',
				'<th class="tRight"><span></span></th>',
			'</tr>',
		'</thead>',
		'<tfoot>',
			'<tr>',
				'<td class="tLeft"><span></span></td>',
				'<td class="tMid"><span></span></td>',
				'<td class="tRight"><span></span></td>',
			'</tr>',
		'</tfoot>',
		'<tbody>',
			'<tr>',
				'<td class="tLeft"><span></span></td>',
				'<td class="tMid" id="#{content}">',
					'<div class="faceItemContent">',
						'<div class="smallface">',
				            '<a onclick="editor.insertFace(\'001\');" title="微笑" href="javascript:;" class="face_ic face_ic001"/>',
				            '<a onclick="editor.insertFace(\'002\');" title="大笑" href="javascript:;" class="face_ic face_ic002"/></a>',
				            '<a onclick="editor.insertFace(\'003\');" title="窃笑" href="javascript:;" class="face_ic face_ic003"/></a>',
				            '<a onclick="editor.insertFace(\'004\');" title="眨眼" href="javascript:;" class="face_ic face_ic004"/></a>',
				            '<a onclick="editor.insertFace(\'005\');" title="做鬼脸" href="javascript:;" class="face_ic face_ic005"/></a>',
				            '<a onclick="editor.insertFace(\'006\');" title="好羡慕哦" href="javascript:;" class="face_ic face_ic006"/></a>',
				            '<a onclick="editor.insertFace(\'007\');" title="呲牙" href="javascript:;" class="face_ic face_ic007"/></a>',
				            '<a onclick="editor.insertFace(\'008\');" title="你好讨厌" href="javascript:;" class="face_ic face_ic008"/></a>',
				            '<a onclick="editor.insertFace(\'009\');" title="愤怒" href="javascript:;" class="face_ic face_ic009"/></a>',
				            '<a onclick="editor.insertFace(\'010\');" title="我真生气了" href="javascript:;" class="face_ic face_ic010"/></a>',
				            '<a onclick="editor.insertFace(\'021\');" title="翻白眼" href="javascript:;" class="face_ic face_ic021"/></a>',
				            '<a onclick="editor.insertFace(\'022\');" title="转向" href="javascript:;" class="face_ic face_ic022"/></a>',
				            '<a onclick="editor.insertFace(\'023\');" title="困惑" href="javascript:;" class="face_ic face_ic023"/></a>',
				            '<a onclick="editor.insertFace(\'024\');" title="睡觉去了" href="javascript:;" class="face_ic face_ic024"/></a>',
				            '<a onclick="editor.insertFace(\'025\');" title="好困呀" href="javascript:;" class="face_ic face_ic025"/></a>',
				            '<a onclick="editor.insertFace(\'026\');" title="闭嘴" href="javascript:;" class="face_ic face_ic026"/></a>',
				            '<a onclick="editor.insertFace(\'027\');" title="真棒" href="javascript:;" class="face_ic face_ic027"/></a>',
 							'<a onclick="editor.insertFace(\'028\');" title="不怎么样" href="javascript:;" class="face_ic face_ic028"/></a>',
				            '<a onclick="editor.insertFace(\'029\');" title="生病" href="javascript:;" class="face_ic face_ic029"/></a>',
				            '<a onclick="editor.insertFace(\'030\');" title="可爱" href="javascript:;" class="face_ic face_ic030"/></a>',
				            '<a onclick="editor.insertFace(\'011\');" title="悲伤" href="javascript:;" class="face_ic face_ic011"/></a>',
				            '<a onclick="editor.insertFace(\'012\');" title="好失望" href="javascript:;" class="face_ic face_ic012"/></a>',
				            '<a onclick="editor.insertFace(\'013\');" title="抓狂" href="javascript:;" class="face_ic face_ic013"/></a>',
				            '<a onclick="editor.insertFace(\'014\');" title="伤心死了" href="javascript:;" class="face_ic face_ic014"/></a>',
				            '<a onclick="editor.insertFace(\'015\');" title="吐你一身" href="javascript:;" class="face_ic face_ic015"/></a>',
				            '<a onclick="editor.insertFace(\'016\');" title="我酷吧" href="javascript:;" class="face_ic face_ic016"/></a>',
				            '<a onclick="editor.insertFace(\'017\');" title="吃惊" href="javascript:;" class="face_ic face_ic017"/></a>',
				            '<a onclick="editor.insertFace(\'018\');" title="好害羞" href="javascript:;" class="face_ic face_ic018"/></a>',
				            '<a onclick="editor.insertFace(\'019\');" title="小声点" href="javascript:;" class="face_ic face_ic019"/></a>',
				            '<a onclick="editor.insertFace(\'020\');" title="再见了" href="javascript:;" class="face_ic face_ic020"/></a>',
				            '<a onclick="editor.insertFace(\'031\');" title="非典" href="javascript:;" class="face_ic face_ic031"/></a>',
				            '<a onclick="editor.insertFace(\'032\');" title="嘴馋" href="javascript:;" class="face_ic face_ic032"/></a>',
				            '<a onclick="editor.insertFace(\'033\');" title="流汗" href="javascript:;" class="face_ic face_ic033"/></a>',
				            '<a onclick="editor.insertFace(\'034\');" title="思考" href="javascript:;" class="face_ic face_ic034"/></a>',
				            '<a onclick="editor.insertFace(\'035\');" title="见钱眼开" href="javascript:;" class="face_ic face_ic035"/></a>',
				            '<a onclick="editor.insertFace(\'036\');" title="好好爱你哟" href="javascript:;" class="face_ic face_ic036"/></a>',
				            '<a onclick="editor.insertFace(\'037\');" title="?" href="javascript:;" class="face_ic face_ic037"/></a>',
				            '<a onclick="editor.insertFace(\'038\');" title="男孩" href="javascript:;" class="face_ic face_ic038"/></a>',
				            '<a onclick="editor.insertFace(\'039\');" title="邮件" href="javascript:;" class="face_ic face_ic039"/></a>',
				            '<a onclick="editor.insertFace(\'040\');" title="热吻" href="javascript:;" class="face_ic face_ic040"/></a>',
				        '</div>',
						'<div class="bigface">',
							'<div id="#{faceTab}" class="faceSidebar">',
							'</div>',
							'<div id="#{faceContent}" class="faceShowAll">',
							'</div>',
						'</div>',
					'</div>',
				'</td>',
				'<td class="tRight"><span></span></td>',
			'</tr>',
		'</tbody>',
	'</table>'
].join("");