// Chinese
plupload.addI18n({
   'Select files' : '选择文件',
   'Add files to the upload queue and click the start button.' : '选择要上传的文件，选择后点击开始按钮开始上传。',
   'Filename' : '文件名称',
   'Status' : '状态',
   'Size' : ' 大小',
   'Add Files' : '添加文件',
   'Stop Upload' : '停止上传',
   'Start Upload' : '开始上传',
   'Add files' : '添加文件',
   'Add files.' : '添加文件',
   'Stop current upload' : '停止当前的上传',
   'Start uploading queue' : '开始批次上传',
   'Stop upload' : '停止上传',
   'Start upload' : '开始上传',
   'Uploaded %d/%d files': '上传了 %d/%d 个文件',
   'N/A' : 'N/A',
   'Drag files here.' : '拖曳要上传的文件到这里',
   'File extension error.': '文件类型错误',
   'File size error.': '文件大小错误',
   'File count error.': '文件数量错误',
   'Init error.': '初始化错误',
   'HTTP Error.': 'HTTP 错误',
   'Security error.': '错误',
   'Generic error.': '错误',
   'IO error.': 'IO 错误',
   'File: %s': '文件: %s',
   'Close': '关闭',
   '%d files queued': '%d 个文件已加入批次',
   'Using runtime: ': '使用: ',
   'File: %f, size: %s, max file size: %m': '文件: %f, 大小: %s, 最大允许: %m',
   'Upload element accepts only %d file(s) at a time. Extra files were stripped.': '上传的文件一次只能 %d 个，其它将不会上传。',
   'Upload URL might be wrong or doesn\'t exist': '上传的网址错误或是不存在。',
   'Error: File too large: ': '错误: 文件太大: ',
   'Error: Invalid file extension: ': '错误: 文件类型不符: '
});
