/**
 * Copyright (c) 2010, Sina Inc. All rights reserved.
 * @fileoverview  元素id哈希表
 * @author dg.liu | dongguang@staff.sina.com.cn
 */
scope.musicHash={
	//tab的容器节点id
	tab_container:"mm_ta_con",
	//”新浪乐库”的容器节点id
	store_container:"mm_st_con",
	//”我的音乐收藏“的容器节点id
	favorite_container:"mm_fa_con",
	//”网络连接”的容器节点id
	web_container:"mm_we_con",
	//”按博客内容自动匹配”的容器节点id
	match_container:"mm_ma_con",
	//插入音乐的容器节点id
	insert_container:"mm_in_con",
	//已选音乐列表节点id
	list_container:"mm_list_con",
	//搜索模块的元素id
	searchItem:"sm_se_item",
	//最热个首模块的元素id
	hotItem:"sm_ho_item",
	//搜素的输入框
	searchInput:"sm_input",
	//搜素的下拉列表框
	searchSelect:"sm_select",
	//搜索提示容器ids
	searchSuggest:"sm_suggest",
	insertButton:"btnInsertMusic",
	//歌曲复选框
	song_checkbox:"sp_so_input_",
	//收藏歌曲复选框
	fav_song_checkbox:'cb_fav_',
	//歌曲复选框
	album_checkbox:"sp_al_input_",
	//搜素列表中的播放按钮
	music_play:"sm_play_",
	appendToLast:"cb_appendToLast",
	//插入歌词
	insertText:"cb_insertLyric",
	//自动播放
	autoButton:'cb_autoPlay'
};
